version: "3.7"

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: princess-key-bot
    volumes:
      - ./:/home/node/app
    command:
      - npm
      - run
      - start
    restart: always
